-- Top Note: Project Planning & Task Management. Run once in Supabase → SQL Editor
-- (or `supabase db push`), after 0001_init.sql. Same conventions as 0001: every table is
-- protected by row level security scoped to auth.uid(), and ids are always supplied by the
-- client (crypto.randomUUID()), never generated by Postgres.

-- ─── Tables ──────────────────────────────────────────────────────────────────

create table if not exists public.projects (
  id           uuid primary key,
  user_id      uuid not null default auth.uid() references auth.users (id) on delete cascade,
  name         text not null check (char_length(name) between 1 and 500),
  description  text not null default '' check (char_length(description) <= 20000),
  start_date   date,
  end_date     date,
  owner        text not null default '' check (char_length(owner) <= 200),
  status       text not null default 'Planning'
                 check (status in ('Planning', 'In Progress', 'On Hold', 'Completed')),
  sort_order   bigint not null default 0,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  deleted_at   timestamptz,
  check (start_date is null or end_date is null or end_date >= start_date)
);
create index if not exists projects_user_idx on public.projects (user_id, sort_order);

create table if not exists public.tasks (
  id              uuid primary key,
  user_id         uuid not null default auth.uid() references auth.users (id) on delete cascade,
  project_id      uuid not null references public.projects (id) on delete cascade,
  parent_task_id  uuid references public.tasks (id) on delete cascade,
  kind            text not null default 'task' check (kind in ('task', 'milestone')),
  name            text not null check (char_length(name) between 1 and 500),
  description     text not null default '' check (char_length(description) <= 20000),
  start_date      date not null,
  end_date        date not null,
  assignee        text not null default '' check (char_length(assignee) <= 200),
  priority        text not null default 'Medium'
                    check (priority in ('Low', 'Medium', 'High', 'Critical')),
  status          text not null default 'To Do'
                    check (status in ('To Do', 'In Progress', 'Review', 'Done')),
  progress        smallint not null default 0 check (progress between 0 and 100),
  notes           text not null default '' check (char_length(notes) <= 20000),
  sort_order      bigint not null default 0,
  revision        integer not null default 0,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  deleted_at      timestamptz,
  check (end_date >= start_date),
  check (kind <> 'milestone' or start_date = end_date)
);
create index if not exists tasks_project_idx on public.tasks (project_id, sort_order);
create index if not exists tasks_parent_idx on public.tasks (parent_task_id);
create index if not exists tasks_user_idx on public.tasks (user_id);

create table if not exists public.task_dependencies (
  id                    uuid primary key,
  user_id               uuid not null default auth.uid() references auth.users (id) on delete cascade,
  predecessor_task_id   uuid not null references public.tasks (id) on delete cascade,
  successor_task_id     uuid not null references public.tasks (id) on delete cascade,
  dependency_type       text not null default 'FS' check (dependency_type in ('FS', 'SS', 'FF', 'SF')),
  created_at            timestamptz not null default now(),
  check (predecessor_task_id <> successor_task_id)
);
create unique index if not exists task_dependencies_unique_idx
  on public.task_dependencies (predecessor_task_id, successor_task_id, dependency_type);
create index if not exists task_dependencies_successor_idx on public.task_dependencies (successor_task_id);
create index if not exists task_dependencies_user_idx on public.task_dependencies (user_id);

create table if not exists public.project_members (
  id          uuid primary key,
  user_id     uuid not null default auth.uid() references auth.users (id) on delete cascade,
  project_id  uuid not null references public.projects (id) on delete cascade,
  name        text not null check (char_length(name) between 1 and 200),
  role        text not null default '' check (char_length(role) <= 200),
  created_at  timestamptz not null default now()
);
create index if not exists project_members_project_idx on public.project_members (project_id);

-- ─── Row level security ─────────────────────────────────────────────────────

alter table public.projects           enable row level security;
alter table public.tasks              enable row level security;
alter table public.task_dependencies  enable row level security;
alter table public.project_members    enable row level security;

do $$
declare t text;
begin
  foreach t in array array['projects', 'tasks', 'task_dependencies', 'project_members'] loop
    execute format('drop policy if exists "own rows" on public.%I', t);
    execute format(
      'create policy "own rows" on public.%I for all to authenticated
         using (user_id = (select auth.uid()))
         with check (user_id = (select auth.uid()))', t);
  end loop;
end $$;

-- ─── Multi-row operations (atomic, run with the caller's RLS) ───────────────

create or replace function public.task_descendants(p_id uuid)
returns setof uuid
language sql stable security invoker set search_path = public as $$
  with recursive tree as (
    select id from public.tasks where id = p_id
    union
    select t.id from public.tasks t join tree x on t.parent_task_id = x.id
  )
  select id from tree;
$$;

-- Forward reachability through the dependency graph (predecessor -> successor edges),
-- used to detect a cycle before a new edge is inserted.
create or replace function public.task_dependency_reachable(p_start uuid)
returns setof uuid
language sql stable security invoker set search_path = public as $$
  with recursive reach as (
    select p_start as id
    union
    select d.successor_task_id from public.task_dependencies d join reach r on d.predecessor_task_id = r.id
  )
  select id from reach where id <> p_start;
$$;

create or replace function public.add_task_dependency(
  p_id uuid, p_predecessor_id uuid, p_successor_id uuid, p_type text default 'FS'
)
returns void
language plpgsql security invoker set search_path = public as $$
declare
  v_pred_project uuid;
  v_succ_project uuid;
begin
  if p_predecessor_id = p_successor_id then
    raise exception 'dependency_self';
  end if;
  select project_id into v_pred_project from public.tasks where id = p_predecessor_id and deleted_at is null;
  select project_id into v_succ_project from public.tasks where id = p_successor_id and deleted_at is null;
  if v_pred_project is null or v_succ_project is null then
    raise exception 'dependency_task_missing';
  end if;
  if v_pred_project <> v_succ_project then
    raise exception 'dependency_cross_project';
  end if;
  -- Adding predecessor -> successor creates a cycle iff successor already (transitively)
  -- precedes predecessor, i.e. predecessor is reachable starting from successor.
  if p_predecessor_id in (select public.task_dependency_reachable(p_successor_id)) then
    raise exception 'dependency_cycle';
  end if;
  insert into public.task_dependencies (id, predecessor_task_id, successor_task_id, dependency_type)
    values (p_id, p_predecessor_id, p_successor_id, p_type)
    on conflict (predecessor_task_id, successor_task_id, dependency_type) do nothing;
end $$;

-- Deletes are soft (deleted_at), so a declarative "on delete cascade" never fires on the
-- normal delete path. This recursively soft-deletes the subtree and hard-deletes any
-- dependency rows that would otherwise dangle, mirroring delete_category's shape.
create or replace function public.delete_task(p_id uuid)
returns void
language plpgsql security invoker set search_path = public as $$
declare ts timestamptz := now();
begin
  update public.tasks set deleted_at = ts, revision = revision + 1, updated_at = ts
    where id in (select public.task_descendants(p_id)) and deleted_at is null;
  delete from public.task_dependencies
    where predecessor_task_id in (select public.task_descendants(p_id))
       or successor_task_id   in (select public.task_descendants(p_id));
end $$;

create or replace function public.delete_project(p_id uuid)
returns void
language plpgsql security invoker set search_path = public as $$
declare ts timestamptz := now();
begin
  update public.projects set deleted_at = ts, updated_at = ts where id = p_id;
  update public.tasks set deleted_at = ts, revision = revision + 1, updated_at = ts
    where project_id = p_id and deleted_at is null;
  delete from public.task_dependencies
    where predecessor_task_id in (select id from public.tasks where project_id = p_id)
       or successor_task_id   in (select id from public.tasks where project_id = p_id);
  delete from public.project_members where project_id = p_id;
end $$;

grant execute on function
  public.task_descendants(uuid),
  public.task_dependency_reachable(uuid),
  public.add_task_dependency(uuid, uuid, uuid, text),
  public.delete_task(uuid),
  public.delete_project(uuid)
to authenticated;
